# Example Cloud Build Configuration File
#
# define the build steps
steps:
  # install the app dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=db-secret --format='get(payload.data)' | tr '_-' '/+' | base64 -d > decrypted-data.txt" ]
    
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "create-env"]
    env:
    - 'DB_CONNECT=${_SECRET_KEY}'
  # execute the tests
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "test"]

  # build an artifact using the docker builder
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$_PROJECT_ID/$_REPO_NAME:latest", "."]

 # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes.yaml
    - --image=gcr.io/$_PROJECT_ID/$_REPO_NAME:latest
    - --location=us-central1-c
    - --cluster=mycluster
  
images:
  - 'gcr.io/$PROJECT_ID/$_REPO_NAME:latest'
